<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LordOfTheRings.Domain\LordOfTheRings.Domain.csproj"/>
        <ProjectReference Include="..\LordOfTheRings.Infrastructure\LordOfTheRings.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Update="SonarAnalyzer.CSharp" Version="10.5.0.109200">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
